Repository nextcloud/files_zip, pull requests merged in 2024-05, with the labels that each got.

#221 Updating phpunit-mysql.yml workflow from template
  .github/workflows/phpunit-mysql.yml
Labels: dependencies

#248 Add SPDX header
  .eslintrc.cjs
  .github/dependabot.yml
  .github/workflows/appstore-build-publish.yml
  .github/workflows/command-rebase.yml
  .github/workflows/lint-eslint-when-unrelated.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node-when-unrelated.yml
  .github/workflows/node.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit-summary-when-unrelated.yml
  .github/workflows/pr-feedback.yml
  .gitignore
  .nextcloudignore
  .php-cs-fixer.dist.php
  .reuse/dep5
  AUTHORS.md
  CHANGELOG.md
  LICENSES/AGPL-3.0-or-later.txt
  LICENSES/Apache-2.0.txt
  LICENSES/CC0-1.0.txt
  LICENSES/MIT.txt
  README.md
  appinfo/info.xml
  appinfo/routes.php
  lib/AppInfo/Application.php
  lib/BackgroundJob/ZipJob.php
  lib/Capabilities.php
  lib/Controller/ZipController.php
  lib/Exceptions/MaximumSizeReachedException.php
  lib/Exceptions/TargetAlreadyExists.php
  lib/InitialState.php
  lib/Listener/LoadAdditionalListener.php
  lib/Notification/Notifier.php
  lib/Service/NotificationService.php
  lib/Service/ZipService.php
  src/Modal.vue
  src/main.d.ts
  src/main.ts
  src/services.ts
  src/types.d.ts
  stylelint.config.cjs
  tests/Feature/ZipFeatureTest.php
  tests/bootstrap.php
  tests/phpunit.xml
  vite.config.ts
Labels: 3. to review, technical debt

#250 Remove duplicate license info
  .github/workflows/reuse.yml
  .reuse/dep5
Labels: 4. to release, technical debt
